# Generated by Django 6.0.5 on 2026-08-28 04:46

import django.core.validators
import django.db.models.deletion
import onibus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_usuario_rua'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onibus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome/Identificação')),
                ('placa', models.CharField(max_length=7, unique=True, verbose_name='Placa')),
                ('capacidade', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='A capacidade mínima é de 1 passageiro.'), django.core.validators.MaxValueValidator(46, message='A capacidade máxima permitida é de 46 passageiros.')], verbose_name='Capacidade')),
                ('foto', models.ImageField(upload_to='onibus/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), onibus.models.validar_tamanho_foto], verbose_name='Foto do veículo')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, max_length=500, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('motorista', models.ForeignKey(limit_choices_to={'tipo': 'motorista'}, on_delete=django.db.models.deletion.PROTECT, related_name='onibus', to='usuarios.usuario', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Ônibus',
                'verbose_name_plural': 'Ônibus',
                'ordering': ['codigo'],
            },
        ),
    ]
